language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest test/unittests.py
#virtualenv:
#  system_site_packages: true
git:
  depth: 2
# safelist
branches:
  only:
  - master
deploy:
- provider: script
  script: now --token $now_token && now alias --token $now_token
  skip_cleanup: true
  on:
    master: true
